name: flutter_dashboard
description: flutter_dashboard – a Flutter package for widgets and UI components.
version: 1.0.1
homepage: https://github.com/vaibhavhariramani/flutter_dashboard

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: 
  progress_loading_button: ^2.0.2
  intl: 
  reactive_forms: ^16.0.1
  equatable: ^2.0.3
  get_storage: ^2.0.3
  get: ^4.6.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

 
